/**
 * Dummy event data for Phase 3.
 * Mirrors the backend `events` row shape defined in EVENT_MAP_FEATURE.md.
 * Replace `eventsAPI.list()` with a real fetch when Phase 1/2 lands.
 */

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const now = Date.now();
const at = (hoursAgo) => new Date(now - hoursAgo * HOUR).toISOString();

let id = 1;
const make = (e) => ({
  id: id++,
  source: e.source ?? 'dummy',
  source_url: e.source_url ?? null,
  title: e.title,
  description: e.description ?? '',
  category: e.category,
  subcategory: e.subcategory ?? null,
  location_name: e.location_name,
  country_iso2: e.country_iso2,
  lat: e.lat,
  lng: e.lng,
  occurred_at: e.occurred_at,
  severity: e.severity,
  market_impact: e.market_impact ?? Math.max(1, e.severity - 2),
  confidence: e.confidence ?? 8,
  affected_sectors: e.affected_sectors ?? [],
  affected_tickers: e.affected_tickers ?? [],
  summary_short: e.summary_short ?? e.title,
});

export const DUMMY_EVENTS = [
  // ──────────────── Conflict / Geopolitics ────────────────
  make({
    title: 'Escalation along eastern Ukrainian front',
    description: 'Heavy artillery exchanges reported near Donetsk; civilian infrastructure damaged.',
    category: 'conflict', subcategory: 'military',
    location_name: 'Donetsk Oblast, Ukraine', country_iso2: 'UA',
    lat: 48.0, lng: 37.8, occurred_at: at(3),
    severity: 8, market_impact: 7,
    affected_sectors: ['defense', 'energy', 'agriculture'],
    affected_tickers: ['LMT', 'RTX', 'NOC', 'XOM', 'ADM'],
    source: 'gdelt',
  }),
  make({
    title: 'Red Sea shipping lane disruption',
    description: 'Tankers diverted around Cape of Good Hope after multiple drone strikes.',
    category: 'conflict', subcategory: 'maritime',
    location_name: 'Bab-el-Mandeb Strait', country_iso2: 'YE',
    lat: 12.6, lng: 43.3, occurred_at: at(8),
    severity: 7, market_impact: 8,
    affected_sectors: ['shipping', 'energy', 'logistics'],
    affected_tickers: ['ZIM', 'MAERSKB.CO', 'XOM', 'CVX', 'BP'],
    source: 'gdelt',
  }),
  make({
    title: 'Border skirmish reported',
    description: 'Limited cross-border fire; both sides claim defensive posture.',
    category: 'conflict',
    location_name: 'Kashmir LoC', country_iso2: 'IN',
    lat: 34.1, lng: 74.4, occurred_at: at(18),
    severity: 6, market_impact: 4,
    affected_sectors: ['defense'], affected_tickers: ['HAL.NS', 'BEL.NS'],
    source: 'gdelt',
  }),
  make({
    title: 'Naval drills heighten regional tension',
    description: 'Large-scale exercises in the Taiwan Strait spark airline reroutes.',
    category: 'conflict', subcategory: 'naval',
    location_name: 'Taiwan Strait', country_iso2: 'TW',
    lat: 24.5, lng: 119.0, occurred_at: at(11),
    severity: 7, market_impact: 9,
    affected_sectors: ['semiconductors', 'defense', 'shipping'],
    affected_tickers: ['TSM', 'NVDA', 'AMD', 'ASML', 'LMT'],
    source: 'gdelt',
  }),

  // ──────────────── Natural disasters ────────────────
  make({
    title: 'M6.4 earthquake off Honshu',
    description: 'Shallow quake 80km offshore; tsunami advisory issued briefly.',
    category: 'disaster_nat', subcategory: 'earthquake',
    location_name: 'Honshu, Japan', country_iso2: 'JP',
    lat: 38.3, lng: 142.2, occurred_at: at(2),
    severity: 7, market_impact: 5,
    affected_sectors: ['insurance', 'manufacturing'],
    affected_tickers: ['7203.T', '6758.T', 'ALL', 'TRV'],
    source: 'usgs',
  }),
  make({
    title: 'M5.8 earthquake near Istanbul',
    category: 'disaster_nat', subcategory: 'earthquake',
    location_name: 'Marmara Sea, Türkiye', country_iso2: 'TR',
    lat: 40.8, lng: 28.9, occurred_at: at(14),
    severity: 6, market_impact: 4,
    affected_sectors: ['insurance', 'construction'],
    affected_tickers: ['XU100.IS'],
    source: 'usgs',
  }),
  make({
    title: 'Wildfire spreads across Northern California',
    description: 'Over 40,000 acres burned; evacuations ordered in three counties.',
    category: 'disaster_nat', subcategory: 'wildfire',
    location_name: 'Shasta County, CA, USA', country_iso2: 'US',
    lat: 40.7, lng: -122.4, occurred_at: at(6),
    severity: 7, market_impact: 5,
    affected_sectors: ['utilities', 'insurance'],
    affected_tickers: ['PCG', 'EIX', 'ALL'],
    source: 'firms',
  }),
  make({
    title: 'Bushfires intensify in New South Wales',
    category: 'disaster_nat', subcategory: 'wildfire',
    location_name: 'New South Wales, Australia', country_iso2: 'AU',
    lat: -33.5, lng: 150.9, occurred_at: at(20),
    severity: 6, market_impact: 3,
    affected_sectors: ['insurance', 'agriculture'],
    affected_tickers: ['IAG.AX', 'QBE.AX'],
    source: 'firms',
  }),
  make({
    title: 'Cyclone makes landfall in Bangladesh',
    description: 'Category 3 storm displaces hundreds of thousands.',
    category: 'disaster_nat', subcategory: 'storm',
    location_name: 'Chittagong, Bangladesh', country_iso2: 'BD',
    lat: 22.3, lng: 91.8, occurred_at: at(30),
    severity: 8, market_impact: 4,
    affected_sectors: ['textiles', 'shipping'],
    affected_tickers: ['HM-B.ST'],
    source: 'reliefweb',
  }),
  make({
    title: 'Volcanic eruption begins on Reykjanes Peninsula',
    category: 'disaster_nat', subcategory: 'volcano',
    location_name: 'Reykjanes, Iceland', country_iso2: 'IS',
    lat: 63.9, lng: -22.5, occurred_at: at(40),
    severity: 6, market_impact: 5,
    affected_sectors: ['airlines', 'tourism'],
    affected_tickers: ['DAL', 'UAL', 'AAL', 'LHA.DE', 'IAG.L'],
    source: 'reliefweb',
  }),
  make({
    title: 'Severe flooding across Rio Grande do Sul',
    category: 'disaster_nat', subcategory: 'flood',
    location_name: 'Porto Alegre, Brazil', country_iso2: 'BR',
    lat: -30.0, lng: -51.2, occurred_at: at(48),
    severity: 7, market_impact: 5,
    affected_sectors: ['agriculture', 'insurance'],
    affected_tickers: ['ADM', 'BG', 'EWZ'],
    source: 'reliefweb',
  }),

  // ──────────────── Politics / Elections ────────────────
  make({
    title: 'Snap election called',
    description: 'PM dissolves parliament, vote scheduled in 6 weeks.',
    category: 'politics', subcategory: 'election',
    location_name: 'London, United Kingdom', country_iso2: 'GB',
    lat: 51.5, lng: -0.13, occurred_at: at(5),
    severity: 6, market_impact: 7,
    affected_sectors: ['banking', 'fx'],
    affected_tickers: ['BARC.L', 'HSBA.L', 'GBPUSD=X'],
    source: 'wikipedia',
  }),
  make({
    title: 'Federal Reserve holds rates, signals one cut in H2',
    category: 'politics', subcategory: 'monetary_policy',
    location_name: 'Washington, DC, USA', country_iso2: 'US',
    lat: 38.9, lng: -77.04, occurred_at: at(10),
    severity: 5, market_impact: 9,
    affected_sectors: ['banking', 'tech', 'real_estate'],
    affected_tickers: ['SPY', 'QQQ', 'TLT', 'XLF', 'JPM'],
    source: 'rss',
  }),
  make({
    title: 'EU passes landmark AI Act amendments',
    category: 'politics', subcategory: 'regulation',
    location_name: 'Brussels, Belgium', country_iso2: 'BE',
    lat: 50.85, lng: 4.35, occurred_at: at(22),
    severity: 5, market_impact: 6,
    affected_sectors: ['tech', 'ai'],
    affected_tickers: ['MSFT', 'GOOGL', 'META', 'NVDA', 'SAP'],
    source: 'rss',
  }),
  make({
    title: 'New sanctions announced against energy sector',
    category: 'politics', subcategory: 'sanctions',
    location_name: 'Tehran, Iran', country_iso2: 'IR',
    lat: 35.7, lng: 51.4, occurred_at: at(28),
    severity: 6, market_impact: 7,
    affected_sectors: ['energy', 'shipping'],
    affected_tickers: ['XOM', 'CVX', 'BNO', 'USO'],
    source: 'gdelt',
  }),
  make({
    title: 'OPEC+ extends voluntary production cuts',
    category: 'politics', subcategory: 'monetary_policy',
    location_name: 'Vienna, Austria', country_iso2: 'AT',
    lat: 48.21, lng: 16.37, occurred_at: at(34),
    severity: 5, market_impact: 8,
    affected_sectors: ['energy'],
    affected_tickers: ['XOM', 'CVX', 'BP', 'SHEL', 'XLE'],
    source: 'rss',
  }),
  make({
    title: 'Presidential election: incumbent wins second term',
    category: 'politics', subcategory: 'election',
    location_name: 'Jakarta, Indonesia', country_iso2: 'ID',
    lat: -6.2, lng: 106.85, occurred_at: at(50),
    severity: 5, market_impact: 5,
    affected_sectors: ['banking', 'commodities'],
    affected_tickers: ['EIDO', 'BBCA.JK'],
    source: 'gdelt',
  }),

  // ──────────────── Protest / Civil unrest ────────────────
  make({
    title: 'Mass protests over pension reform',
    description: 'Estimated 500k in the streets; metro shutdown across Paris.',
    category: 'protest',
    location_name: 'Paris, France', country_iso2: 'FR',
    lat: 48.85, lng: 2.35, occurred_at: at(9),
    severity: 6, market_impact: 4,
    affected_sectors: ['retail', 'tourism'],
    affected_tickers: ['MC.PA', 'OR.PA'],
    source: 'gdelt',
  }),
  make({
    title: 'Farmers block highways nationwide',
    category: 'protest',
    location_name: 'Berlin, Germany', country_iso2: 'DE',
    lat: 52.52, lng: 13.4, occurred_at: at(16),
    severity: 5, market_impact: 4,
    affected_sectors: ['agriculture', 'logistics'],
    affected_tickers: ['BAYN.DE', 'DPW.DE'],
    source: 'gdelt',
  }),
  make({
    title: 'University strikes spread across major cities',
    category: 'protest',
    location_name: 'Buenos Aires, Argentina', country_iso2: 'AR',
    lat: -34.6, lng: -58.4, occurred_at: at(26),
    severity: 4, market_impact: 3,
    affected_sectors: ['education'],
    affected_tickers: ['ARGT'],
    source: 'gdelt',
  }),
  make({
    title: 'Anti-government rallies in capital',
    category: 'protest',
    location_name: 'Tbilisi, Georgia', country_iso2: 'GE',
    lat: 41.7, lng: 44.8, occurred_at: at(35),
    severity: 5, market_impact: 2,
    source: 'gdelt',
  }),

  // ──────────────── Economy ────────────────
  make({
    title: 'Major chipmaker reports record quarterly revenue',
    category: 'economy', subcategory: 'earnings',
    location_name: 'Hsinchu, Taiwan', country_iso2: 'TW',
    lat: 24.8, lng: 120.97, occurred_at: at(4),
    severity: 4, market_impact: 8,
    affected_sectors: ['semiconductors'],
    affected_tickers: ['TSM', 'NVDA', 'AMD', 'AVGO', 'SOXX'],
    source: 'rss',
  }),
  make({
    title: 'Port workers strike enters second week',
    category: 'economy', subcategory: 'labor',
    location_name: 'Hamburg, Germany', country_iso2: 'DE',
    lat: 53.55, lng: 9.99, occurred_at: at(7),
    severity: 5, market_impact: 6,
    affected_sectors: ['shipping', 'logistics', 'retail'],
    affected_tickers: ['MAERSKB.CO', 'AMZN', 'WMT'],
    source: 'rss',
  }),
  make({
    title: 'Central bank surprise rate hike',
    category: 'economy', subcategory: 'monetary_policy',
    location_name: 'Tokyo, Japan', country_iso2: 'JP',
    lat: 35.68, lng: 139.69, occurred_at: at(13),
    severity: 4, market_impact: 9,
    affected_sectors: ['banking', 'fx', 'global_macro'],
    affected_tickers: ['EWJ', 'USDJPY=X', 'NKE'],
    source: 'rss',
  }),
  make({
    title: 'Sovereign default risk rises after S&P downgrade',
    category: 'economy', subcategory: 'credit',
    location_name: 'Cairo, Egypt', country_iso2: 'EG',
    lat: 30.04, lng: 31.24, occurred_at: at(24),
    severity: 6, market_impact: 5,
    affected_sectors: ['emerging_markets', 'bonds'],
    affected_tickers: ['EMB'],
    source: 'rss',
  }),

  // ──────────────── Health ────────────────
  make({
    title: 'New respiratory outbreak under investigation',
    description: 'WHO dispatches team after cluster of severe pneumonia cases.',
    category: 'health',
    location_name: 'Hanoi, Vietnam', country_iso2: 'VN',
    lat: 21.03, lng: 105.85, occurred_at: at(12),
    severity: 6, market_impact: 5,
    affected_sectors: ['pharma', 'travel'],
    affected_tickers: ['PFE', 'MRNA', 'DAL', 'UAL'],
    source: 'reliefweb',
  }),
  make({
    title: 'Bird flu detected in commercial poultry farms',
    category: 'health',
    location_name: 'Iowa, USA', country_iso2: 'US',
    lat: 41.88, lng: -93.1, occurred_at: at(38),
    severity: 5, market_impact: 4,
    affected_sectors: ['agriculture', 'food'],
    affected_tickers: ['TSN', 'PPC'],
    source: 'reliefweb',
  }),

  // ──────────────── Discovery / Science ────────────────
  make({
    title: 'Major lithium reserve discovered',
    description: 'Geological survey confirms one of the largest known deposits.',
    category: 'discovery',
    location_name: 'Salar de Uyuni, Bolivia', country_iso2: 'BO',
    lat: -20.13, lng: -67.49, occurred_at: at(17),
    severity: 4, market_impact: 7,
    affected_sectors: ['mining', 'ev'],
    affected_tickers: ['LIT', 'ALB', 'TSLA', 'BYD'],
    source: 'wikipedia',
  }),
  make({
    title: 'Particle collider observes unexpected resonance',
    category: 'discovery',
    location_name: 'CERN, Geneva, Switzerland', country_iso2: 'CH',
    lat: 46.23, lng: 6.05, occurred_at: at(27),
    severity: 3, market_impact: 1,
    source: 'wikipedia',
  }),
  make({
    title: 'Successful lunar lander touchdown',
    category: 'discovery', subcategory: 'space',
    location_name: 'Bangalore, India', country_iso2: 'IN',
    lat: 12.97, lng: 77.59, occurred_at: at(44),
    severity: 4, market_impact: 4,
    affected_sectors: ['aerospace'],
    affected_tickers: ['HAL.NS', 'LMT', 'BA'],
    source: 'rss',
  }),

  // ──────────────── Disaster_hum ────────────────
  make({
    title: 'Famine conditions declared in Tigray',
    category: 'disaster_hum',
    location_name: 'Mekelle, Ethiopia', country_iso2: 'ET',
    lat: 13.5, lng: 39.47, occurred_at: at(60),
    severity: 8, market_impact: 2,
    affected_sectors: ['agriculture'],
    source: 'reliefweb',
  }),
  make({
    title: 'Refugee crisis intensifies at southern border',
    category: 'disaster_hum',
    location_name: 'Darién Gap, Panama', country_iso2: 'PA',
    lat: 8.1, lng: -77.5, occurred_at: at(70),
    severity: 6, market_impact: 1,
    source: 'reliefweb',
  }),

  // A few smaller / older
  make({
    title: 'Local power outage affects 200k',
    category: 'economy',
    location_name: 'Lagos, Nigeria', country_iso2: 'NG',
    lat: 6.5, lng: 3.4, occurred_at: at(90),
    severity: 4, market_impact: 2,
    source: 'rss',
  }),
  make({
    title: 'Cybersecurity breach at major bank disclosed',
    category: 'economy',
    location_name: 'Singapore', country_iso2: 'SG',
    lat: 1.3, lng: 103.85, occurred_at: at(54),
    severity: 5, market_impact: 5,
    affected_sectors: ['banking', 'cybersecurity'],
    affected_tickers: ['DBS', 'CRWD', 'PANW'],
    source: 'rss',
  }),
];

export const CATEGORIES = [
  { id: 'conflict',     label: 'Conflict',        color: '#ef4444' },
  { id: 'protest',      label: 'Protest',         color: '#f59e0b' },
  { id: 'politics',     label: 'Politics',        color: '#8b5cf6' },
  { id: 'disaster_nat', label: 'Natural disaster', color: '#22d3ee' },
  { id: 'disaster_hum', label: 'Humanitarian',    color: '#a78bfa' },
  { id: 'economy',      label: 'Economy',         color: '#10b981' },
  { id: 'health',       label: 'Health',          color: '#ec4899' },
  { id: 'discovery',    label: 'Discovery',       color: '#06b6d4' },
  { id: 'other',        label: 'Other',           color: '#94a3b8' },
];

export const CATEGORY_COLOR = Object.fromEntries(CATEGORIES.map((c) => [c.id, c.color]));
export const CATEGORY_LABEL = Object.fromEntries(CATEGORIES.map((c) => [c.id, c.label]));
